### ISSUE TITLE
Watch shows incorrect notifications 

### ISSUE THREAD

**Issue by Zipp05** [GreatApo/GreatFit#21]
My watch Pace shows that I have 7 missed notifications. But when I pull up, my watch says all caught up. Therefore no missed notifications. I tried restarting watch but didn't work. Change to another watchface and back to GreatFit didn't work. How can we synch this? Using with AmazMod.

**Comment by GreatApo** [comment]
Notifications have to be pushed to watch through Amazmod. Probably your connection is dropped and the counter is not upgraded...

There may be time that the tracking system doesn't work correctly like when the watch goes in power save mode (since the amazmod connection is dropped).

On the other hand, you may see some differences in the notifications and the counter because of the ungrouped notifications, but it just adds the messages you haven't seen. It goes back to normal when you swipe the notification in your phone.

**Comment by Zipp05** [comment]
I tried sending WhatsApp to myself. When I delete them on my watch counter stays 1. On my phone you also see 1 notification. When I delete or read from phone counter drops to 0. Or if you send an pre saved answer on your watch it also goes to 0, Notification on watch is also 0.

I think it is connected with my notification bar on my phone. And something went wrong. But it Is working now. I will monitor this. Thanks. It still is the best watchface I've seen so far :)

**Comment by GreatApo** [comment]
> I tried sending WhatsApp to myself. When I delete them on my watch counter stays 1. On my phone you also see 1 notification. When I delete or read from phone counter drops to 0. Or if you send an pre saved answer on your watch it also goes to 0, Notification on watch is also 0.
> 
> I think it is connected with my notification bar on my phone. And something went wrong. But it Is working now. I will monitor this. Thanks. It still is the best watchface I've seen so far :)

Yeah, this is exactly how it works since we don't have access to watch's notification management system.
